# Default initial positions for humanoid's ros2_control fake system

initial_positions:
  elbow_pitch_l_joint: 0
  elbow_pitch_r_joint: 0
  elbow_yaw_l_joint: 0
  elbow_yaw_r_joint: 0
  shoulder_pitch_l_joint: 0
  shoulder_pitch_r_joint: 0
  shoulder_roll_l_joint: 0
  shoulder_roll_r_joint: 0
  shoulder_yaw_l_joint: 0
  shoulder_yaw_r_joint: 0
  wrist_pitch_l_joint: 0
  wrist_pitch_r_joint: 0
  wrist_roll_l_joint: 0
  wrist_roll_r_joint: 0