# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - shoulder_pitch_l_joint
      - shoulder_roll_l_joint
      - shoulder_yaw_l_joint
      - elbow_pitch_l_joint
      - elbow_yaw_l_joint
      - wrist_pitch_l_joint
      - wrist_roll_l_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - shoulder_pitch_r_joint
      - shoulder_roll_r_joint
      - shoulder_yaw_r_joint
      - elbow_pitch_r_joint
      - elbow_yaw_r_joint
      - wrist_pitch_r_joint
      - wrist_roll_r_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity